/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;


public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException {

//          import image
        BufferedImage image = Bitmap.bitmapImport();

//          rotate image
        if (args[0].equals("rotate")){
            System.out.println("-- rotating --");
            BufferedImage rotatedImage = Bitmap.rotate(image);
            ImageIO.write(rotatedImage,"BMP", new File("src/test/resources/rotateImage.bmp"));
        } else {
            System.out.println("only rotating right now");
        }

//          scale the image
        BufferedImage scaledImage = Bitmap.scaleImage(image);


//        write the transformed file
        ImageIO.write(scaledImage, "BMP", new File("src/test/resources/scaledImage.bmp"));

    }



}
